mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: /mapper/*Mapper.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.112.23.59:3306/axi?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: shaojiaxi
